version: '3'
services:

  ise-exporter:
    container_name: ise-exporter
    build:
      dockerfile: Dockerfile
      context: ./ise-exporter
    ports:
      - 3000:3000
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    environment:
      - PROMETHEUS_USERNAME=admin
      - PROMETHEUS_PASSWORD=admin
      - PROMETHEUS_URL=http://localhost:9090
      - PROMETHEUS_TOKEN=
    depends_on:
      - ise-exporter
    restart: always
  grafana:
    container_name: grafana
    build: 
      dockerfile: Dockerfile
      context: ./grafana
    image: grafana/grafana-oss
    ports:
      - 3001:3000
