{
 "title": "Cisco ISE Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_total_endpoints{type=\"total\"}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_total_endpoints{type=\"active\"}"
    }
   ]
  },
  {
   "title": "BYOD Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_total_endpoints{type=\"byod\"}"
    }
   ]
  },
  {
   "title": "Authenticated Guests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ise_authenticated_guests{}" }
   ]
  },
  {
   "title": "CPU Gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ise_cpu{}" }
   ]
  },
  {
   "title": "Memory Gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ise_cpu{}" }
   ]
  },
  {
   "title": "Auth Latency (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(ise_auth_latency[1m])) / sum(count_over_time(ise_auth_latency[1m]))"
    }
   ]
  },
  {
   "title": "Rejected Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_total_endpoints{type=\"rejected\"}"
    }
   ]
  },
  {
   "title": "Anamolous Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_total_endpoints{type=\"anomalous\"}"
    }
   ]
  },
  {
   "title": "Misconfigured NAS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_misconfigured_count{type=\"misconfigured_nas\"}"
    }
   ]
  },
  {
   "title": "Misconfigured Supplicants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_misconfigured_count{type=\"misconfigured_supplicant\"}"
    }
   ]
  },
  {
   "title": "Connect Compromised Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_top_compromised_endpoints_count{status=\"connected\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ise_cpu{}", "legendFormat": "{{node}} - {{personas}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ise_memory{}", "legendFormat": "{{node}} - {{personas}}" }
   ]
  },
  {
   "title": "Authentication Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ise_auth_latency{}", "legendFormat": "{{node}} - {{personas}}" }
   ]
  },
  {
   "title": "Endpoint Profiles (Piechart)",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 12 },
   "targets": [
    { "expr": "ise_endpoint_profiles{}", "legendFormat": "{{endpoint_profile}}" }
   ]
  },
  {
   "title": "Endpoint Profiles",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 12 },
   "targets": [
    { "expr": "ise_endpoint_profiles{}", "legendFormat": "{{endpoint_profile}}" }
   ]
  },
  {
   "title": "Logical Profiles",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 3, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ise_logical_profiles{}", "legendFormat": "{{logical_profile}}" }
   ]
  },
  {
   "title": "Endpoint Identity Groups",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 3, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ise_endpoint_identity_groups{}", "legendFormat": "{{identity_group}}" }
   ]
  },
  {
   "title": "Endpoint Count by Network Device Location",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "sum by (device_location) (ise_endpoints_by_network_device)",
     "legendFormat": "{{device_location}}"
    }
   ]
  },
  {
   "title": "Endpoint Count by Network Device Location",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sum by (device_location) (ise_endpoints_by_network_device)",
     "legendFormat": "{{device_location}}"
    }
   ]
  },
  {
   "title": "Endpoint Threats by Severity",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ise_top_threats_by_severity_count{status=\"all\"}",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Endpoint Threats by Severity Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 3, "y": 25 },
   "targets": [
    {
     "expr": "ise_top_threats_by_severity_count{status=\"all\"}",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Endpoint Threats by Threat Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 3, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(ise_top_threats_by_threat_count{status=\"connected\"})",
     "legendFormat": "{{threat_name}}"
    }
   ]
  },
  {
   "title": "Endpoint Threats by Threat Type Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(ise_top_threats_by_threat_count{status=\"connected\"})",
     "legendFormat": "{{threat_name}}"
    }
   ]
  },
  {
   "title": "RADIUS Repeat Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 2, "x": 18, "y": 25 },
   "targets": [
    { "expr": "ise_radius_repeat_count{}", "legendFormat": "RADIUS Repeat Count" }
   ]
  },
  {
   "title": "RADIUS Drop Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 2, "x": 20, "y": 25 },
   "targets": [
    { "expr": "ise_radius_drop_count{}", "legendFormat": "RADIUS Drop Count" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 12, "w": 2, "x": 22, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ise_radius_drop_percent{}", "legendFormat": "RADIUS Drop Count" }
   ]
  }
 ]
}